// Generated by `wrangler types` - run `npm run types` to regenerate
interface Env {
  EMAIL: Fetcher;
  SUPABASE_URL: string;
  SUPABASE_SERVICE_KEY: string;
  GEMINI_API_KEY: string;
  RESEND_API_KEY: string;
  DIGEST_RECIPIENT_EMAIL: string;
  OPENWEATHER_API_KEY: string;
}
