import { NextResponse } from "next/server";
import { errorResponse, getAuthedSupabase } from "@/lib/api";
import { generateTripKnowledgeStarter, getTripKnowledgeExtractionTags } from "@/lib/trip-knowledge-extraction";

type Params = { params: Promise<{ id: string }> };

export async function POST(_: Request, { params }: Params) {
  const auth = await getAuthedSupabase();
  if (auth.error || !auth.supabase || !auth.user) return auth.error;

  const apiKey = process.env.GEMINI_API_KEY?.trim();
  if (!apiKey) {
    return errorResponse("GEMINI_API_KEY is not configured on the server.", 503);
  }

  const { id } = await params;
  const { data: trip, error: tripError } = await auth.supabase
    .from("trips")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (tripError) return errorResponse(tripError.message, 500);
  if (!trip) return errorResponse("Trip not found", 404);

  const { data: existingKnowledge, error: knowledgeError } = await auth.supabase
    .from("trip_knowledge_items")
    .select("title")
    .eq("trip_id", id)
    .order("created_at", { ascending: false });
  if (knowledgeError) return errorResponse(knowledgeError.message, 500);

  let extraction: Awaited<ReturnType<typeof generateTripKnowledgeStarter>>;
  try {
    extraction = await generateTripKnowledgeStarter(apiKey, {
      title: trip.title,
      destination: trip.destination,
      start_date: trip.start_date,
      end_date: trip.end_date,
      logistics: trip.logistics,
      logistics_details: trip.logistics_details,
      adult_count: trip.adult_count ?? 0,
      kid_count: trip.kid_count ?? 0,
      kid_ages: Array.isArray(trip.kid_ages) ? trip.kid_ages : [],
      already_done: trip.already_done,
      preferences: trip.preferences,
      selected_preferences: Array.isArray(trip.selected_preferences) ? trip.selected_preferences : [],
      existing_knowledge_titles: (existingKnowledge ?? []).map((item) => item.title).filter(Boolean),
    });
  } catch (error) {
    return errorResponse(error instanceof Error ? error.message : "Failed to generate trip knowledge starter", 500);
  }

  const now = new Date().toISOString();
  const { data: knowledge, error: insertError } = await auth.supabase
    .from("trip_knowledge_items")
    .insert({
      trip_id: id,
      title: "AI starter places and activities",
      source_url: null,
      raw_markdown: "Generated by AI from trip logistics, preferences, and avoid-repeat context.",
      extraction_focus: "both",
      extraction,
      tags: getTripKnowledgeExtractionTags(extraction),
      status: "processed",
      error_message: null,
      extracted_at: now,
    })
    .select("*")
    .single();

  if (insertError || !knowledge) {
    return errorResponse(insertError?.message ?? "Failed to save trip knowledge starter", 500);
  }

  return NextResponse.json({ knowledge }, { status: 201 });
}
